name: boilerplate
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # A
  another_flushbar: ^1.12.30
  # B
  # C
  cupertino_icons: ^1.0.8
  # D
  dio: ^5.5.0+1
  # E
  event_bus: ^2.0.0
  # F
  flutter_mobx: ^2.2.1+1
  # G
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  # H
  http: ^1.2.2
  # I
  intl: ^0.19.0
  # J
  json_serializable: ^6.8.0
  # K
  # L
  # M
  mobx: ^2.3.3+2
  # N
  # O
  # P
  path_provider: ^2.1.4
  # Q
  # R
  # S
  shared_preferences: ^2.3.0
  sembast_web: ^2.4.0+2
  sembast: ^3.7.1+3
  # T
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  # Y
  # Z

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11
  analyzer: ^5.13.0



flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/
  - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: ProductSans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
      style: italic
    - asset: assets/fonts/Product-Sans-Bold.ttf
      weight: 700
